import {
  ClockViewModel,
  createWorldImagery,
  EllipsoidTerrainProvider,
  createDefaultImageryProviderViewModels,
  createDefaultTerrainProviderViewModels,
  SceneMode,
  GeographicProjection,
  Globe,
  DataSourceCollection,
  ShadowMode,
  MapMode2D,
} from "cesium";

const CESIUM_CONFIG = {
  animation: false,
  baseLayerPicker: false,
  fullscreenButton: false,
  // vrButton: false,
  geocoder: false,
  homeButton: false,
  infoBox: false,
  // sceneModePicker: true,
  // selectionIndicator: true,
  timeline: false,
  navigationHelpButton: false,
  navigationInstructionsInitiallyVisible: false,
  scene3DOnly: true,
  // shouldAnimate: false,
  // clockViewModel: new ClockViewModel(clock),
  // selectedImageryProviderViewModel: null,
  // imageryProviderViewModels: createDefaultImageryProviderViewModels(),
  // selectedTerrainProviderViewModel: null,
  // terrainProviderViewModels: createDefaultTerrainProviderViewModels(),
  // imageryProvider: createWorldImagery(),
  // terrainProvider: new EllipsoidTerrainProvider(),
  skyBox: false,
  // skyAtmosphere: false,
  // fullscreenElement: document.body,
  // useDefaultRenderLoop: true,
  // targetFrameRate: 60,
  // showRenderLoopErrors: true,
  // useBrowserRecommendedResolution: true,
  // automaticallyTrackDataSourceClocks: true,
  // contextOptions: null,
  // sceneMode: SceneMode.SCENE3D,
  // mapProjection: new GeographicProjection(),
  // globe: false,
  // orderIndependentTranslucency: true,
  creditContainer: document.createElement("div"),
  // creditViewport: null,
  // dataSources: new DataSourceCollection(),
  // shadows: false,
  // terrainShadows: ShadowMode.RECEIVE_ONLY,
  // mapMode2D: MapMode2D.INFINITE_SCROLL,
  // projectionPicker: false,
  // blurActiveElementOnCanvasFocus: true,
  // requestRenderMode: false,
  // maximumRenderTimeChange: 0.0,
  // depthPlaneEllipsoidOffset: 0.0,
  // msaaSamples: 1,
};

export { CESIUM_CONFIG };
